### Validator address

bitsongvaloper1aakd7kru6n9l2ty565j3t893ygadc9xz0c65mk

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

https://nodtech.eu/  , @zVOLz

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem

### Details

Professional validators. Supported Bitsong from first testnet. Fast upgrades and good reaction.
Website https://nodtech.eu/
Twitter https://twitter.com/nodtecheu
Telegram https://t.me/nodtechee


### Goals

Goals long-term participation in the project,  active governance, spred info about Bitsong, create content , and support in social media!

### Timetable

_No response_
